<a href="https://colab.research.google.com/github/JGarciaGal/MetNumUN2023I/blob/main/Quices/Test_1_NM_2023_I_UNCode_Programming_Assignment_jgarciagal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Test 1 NM 2023 I UNCode Programming Assignment**




#**|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||**#

#**1. Modify the given optimized code for PLU factorization to generate the sequence of transfromations from $A$,$U_1$,$U_2$,$\cdots$,$U_{n-2}$ to the uppper tiangular matrix $U$** 







In [ ]:
import numpy as np
def diy_lu_optimized(a):
    
    N = a.shape[0]  # Get the number of rows in the input matrix
    
    U = np.array(a.copy(),dtype=float)  # Create a copy of the input matrix to store the upper triangular matrix
    L = np.eye(N)  # Initialize L as an identity matrix of size N
    P = np.eye(N)  # Initialize P as an identity matrix of size N (permutation matrix)
    transformations = []
    for j in range(N - 1):
        pivot_row = np.argmax(np.abs(U[j:, j])) + j  # Find the pivot row for column j
        
        if pivot_row != j:
            U[[j, pivot_row], :j+1] = U[[pivot_row, j], :j+1]  # Swap rows in U matrix
            P[[j, pivot_row], :] = P[[pivot_row, j], :]  # Update permutation matrix
            if j >= 1:
                L[[j, pivot_row], :j] = L[[pivot_row, j], :j]  # Update L matrix
        
        gamma = U[j+1:, j] / U[j, j]  # Calculate the multipliers for elimination
        
        U[j+1:, j:] -= gamma[:, np.newaxis] * U[j, j:]  # Update the remaining part of the U matrix
        L[j+1:, j] = gamma  # Update the lower part of the L matrix
        if j == N-2:
            transformations.append(U.copy())
    return P, L, transformations[-1]  # Return the permutation matrix P, lower triangular matrix L, and upper triangular matrix U

$$ \Lambda_1 P_1 A  = U_1 $$  
$$ \Lambda_2 P_2 U_1  = U_2$$
$$\vdots$$
$$\Lambda_{n-1} P_{n-1} U_{n-2} = U$$

---

###**Problem Description**


**Task:** Given a square matrix $A$ generate the sequence of transformations from $A$,$U_1$,$U_2$,$\cdots$,$U_{n-2}$ to the uppper tiangular matrix $U$ and the sequence of row swaps performed.

---

**Input Format:** the square matrix $A$ is a numpy square matrix.

**Output Format:** A tuple of the sequence of transformations [$A$,$U_1$,$U_2$,$\cdots$,$U_{n-2}$,$U$] is a list of numpy matrices with its elements rounded to $3$ decimal places and  the sequence of row swaps is a list of sorted tuples of the indices of the rows swapped.

---







**Sample testcases**

```python
#run this sample textcases on a cell to help you validate your solution

A = np.array([[4,3,1], [5,7,0], [9,9,3]])

diy_lu_optimized_sequences(A)

#  --> Expected output: ([array([[4., 3., 1.],
         [5., 7., 0.],
         [9., 9., 3.]]),
  array([[ 9.   ,  3.   ,  1.   ],
         [ 0.   ,  5.333, -0.556],
         [ 0.   ,  7.667,  2.556]]),
  array([[ 9.   ,  3.   ,  1.   ],
         [ 0.   ,  7.667, -0.556],
         [ 0.   ,  0.   ,  2.942]])],
 [(0, 2), (1, 2)])

A = np.array([[1,2,3,4], [2,3,4,5], [0,1,2,3],[6,7,8,9]])

diy_lu_optimized_sequences(A)

#  --> Expected output: ([array([[1., 2., 3., 4.],
         [2., 3., 4., 5.],
         [0., 1., 2., 3.],
         [6., 7., 8., 9.]]),
  array([[6.   , 2.   , 3.   , 4.   ],
         [0.   , 2.333, 3.   , 3.667],
         [0.   , 1.   , 2.   , 3.   ],
         [0.   , 6.667, 7.5  , 8.333]]),
  array([[6.   , 2.   , 3.   , 4.   ],
         [0.   , 6.667, 3.   , 3.667],
         [0.   , 0.   , 1.55 , 2.45 ],
         [0.   , 0.   , 6.45 , 7.05 ]]),
  array([[6.   , 2.   , 3.   , 4.   ],
         [0.   , 6.667, 3.   , 3.667],
         [0.   , 0.   , 6.45 , 2.45 ],
         [0.   , 0.   , 0.   , 6.461]])],
 [(0, 3), (1, 3), (2, 3)])
```

---

**Solution**

In [ ]:
import numpy as np
def diy_lu_optimized_sequences(a):
  
  U_sequence =[]
  P_sequence =[]
  
  U = np.array(a.copy(),dtype=float)  # Create a copy of the input matrix to store the upper triangular matrix
  L = np.eye(N)  # Initialize L as an identity matrix of size N
  P = np.eye(N)  # Initialize P as an identity matrix of size N (permutation matrix)
  U_sequence = []
  for j in range(N - 1):
      pivot_row = np.argmax(np.abs(U[j:, j])) + j  # Find the pivot row for column j
        
      if pivot_row != j:
          U[[j, pivot_row], :j+1] = U[[pivot_row, j], :j+1]  # Swap rows in U matrix
          P[[j, pivot_row], :] = P[[pivot_row, j], :]  # Update permutation matrix
          if j >= 1:
              L[[j, pivot_row], :j] = L[[pivot_row, j], :j]  # Update L matrix
          p_secuence.append((j, pivot_row))
           
      gamma = U[j+1:, j] / U[j, j]  # Calculate the multipliers for elimination
      U_sequence.append(U.copy()) 
      U[j+1:, j:] -= gamma[:, np.newaxis] * U[j, j:]  # Update the remaining part of the U matrix
      L[j+1:, j] = gamma  # Update the lower part of the L matrix
      if j == N-2:
            U_sequence.append(U.copy())
  return U_sequence,P_sequence  #DO NOT change this line. Output will be read as a tuple.

In [ ]:
A = np.array([[4,3,1], [5,7,0], [9,9,3]])

diy_lu_optimized(A)

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.44444444, 1.        , 0.        ],
        [0.55555556, 0.69565217, 1.        ]]),
 array([[ 9.        ,  3.        ,  1.        ],
        [ 0.        ,  7.66666667, -0.55555556],
        [ 0.        ,  0.        ,  2.94202899]]))